services:
  server:
    container_name: example_server
    build:
      context: etc/server
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app:/app
  app:
    container_name: example_app
    build:
      target: ${APP_ENV}
      context: etc/app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./etc/app/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/z-php-fpm.conf
    depends_on:
      db:
        condition: service_healthy
    tty: true
    working_dir: /app
  db:
    container_name: example_db
    build:
      context: etc/db
      dockerfile: Dockerfile
    volumes:
      - database:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    tty: true
    working_dir: /app

volumes:
  database:
    driver: local
